# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f08887ae8587d22498097f82feb87a68720b0305b00d3cc87e63dfe5a5dd1646d2c90eb98d69c1375adc6a07ff5df4125a38a4a77e91b22d3425e17232073dbc

test:
  secret_key_base: cad6f7fce1de87141aeeb1bd6479c2eb54670cbdd9d9de99f0ee6a5252380ccdce717a774ec428765522379c97fe3d291d964c6e0773a99746460899a213d729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
